// Code generated by protoc-gen-go. DO NOT EDIT.
// source: plugin.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	v1 "k8s.io/api/core/v1"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// InitConfig is passed to the provider on initialization
type InitConfig struct {
	ConfigPath           string   `protobuf:"bytes,1,opt,name=configPath,proto3" json:"configPath,omitempty"`
	NodeName             string   `protobuf:"bytes,2,opt,name=nodeName,proto3" json:"nodeName,omitempty"`
	OperatingSystem      string   `protobuf:"bytes,3,opt,name=operatingSystem,proto3" json:"operatingSystem,omitempty"`
	InternalIP           string   `protobuf:"bytes,4,opt,name=internalIP,proto3" json:"internalIP,omitempty"`
	DaemonPort           int32    `protobuf:"varint,5,opt,name=DaemonPort,proto3" json:"DaemonPort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *InitConfig) Reset()         { *m = InitConfig{} }
func (m *InitConfig) String() string { return proto.CompactTextString(m) }
func (*InitConfig) ProtoMessage()    {}
func (*InitConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{0}
}

func (m *InitConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_InitConfig.Unmarshal(m, b)
}
func (m *InitConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_InitConfig.Marshal(b, m, deterministic)
}
func (m *InitConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_InitConfig.Merge(m, src)
}
func (m *InitConfig) XXX_Size() int {
	return xxx_messageInfo_InitConfig.Size(m)
}
func (m *InitConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_InitConfig.DiscardUnknown(m)
}

var xxx_messageInfo_InitConfig proto.InternalMessageInfo

func (m *InitConfig) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *InitConfig) GetNodeName() string {
	if m != nil {
		return m.NodeName
	}
	return ""
}

func (m *InitConfig) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

func (m *InitConfig) GetInternalIP() string {
	if m != nil {
		return m.InternalIP
	}
	return ""
}

func (m *InitConfig) GetDaemonPort() int32 {
	if m != nil {
		return m.DaemonPort
	}
	return 0
}

type ProviderRegisterRequest struct {
	InitConfig           *InitConfig `protobuf:"bytes,1,opt,name=initConfig,proto3" json:"initConfig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *ProviderRegisterRequest) Reset()         { *m = ProviderRegisterRequest{} }
func (m *ProviderRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*ProviderRegisterRequest) ProtoMessage()    {}
func (*ProviderRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{1}
}

func (m *ProviderRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderRegisterRequest.Unmarshal(m, b)
}
func (m *ProviderRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderRegisterRequest.Marshal(b, m, deterministic)
}
func (m *ProviderRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderRegisterRequest.Merge(m, src)
}
func (m *ProviderRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_ProviderRegisterRequest.Size(m)
}
func (m *ProviderRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderRegisterRequest proto.InternalMessageInfo

func (m *ProviderRegisterRequest) GetInitConfig() *InitConfig {
	if m != nil {
		return m.InitConfig
	}
	return nil
}

type ProviderRegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProviderRegisterResponse) Reset()         { *m = ProviderRegisterResponse{} }
func (m *ProviderRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*ProviderRegisterResponse) ProtoMessage()    {}
func (*ProviderRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{2}
}

func (m *ProviderRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProviderRegisterResponse.Unmarshal(m, b)
}
func (m *ProviderRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProviderRegisterResponse.Marshal(b, m, deterministic)
}
func (m *ProviderRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProviderRegisterResponse.Merge(m, src)
}
func (m *ProviderRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_ProviderRegisterResponse.Size(m)
}
func (m *ProviderRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ProviderRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ProviderRegisterResponse proto.InternalMessageInfo

type CreatePodRequest struct {
	Pod                  *v1.Pod  `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePodRequest) Reset()         { *m = CreatePodRequest{} }
func (m *CreatePodRequest) String() string { return proto.CompactTextString(m) }
func (*CreatePodRequest) ProtoMessage()    {}
func (*CreatePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{3}
}

func (m *CreatePodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodRequest.Unmarshal(m, b)
}
func (m *CreatePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodRequest.Marshal(b, m, deterministic)
}
func (m *CreatePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodRequest.Merge(m, src)
}
func (m *CreatePodRequest) XXX_Size() int {
	return xxx_messageInfo_CreatePodRequest.Size(m)
}
func (m *CreatePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodRequest proto.InternalMessageInfo

func (m *CreatePodRequest) GetPod() *v1.Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

type CreatePodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatePodResponse) Reset()         { *m = CreatePodResponse{} }
func (m *CreatePodResponse) String() string { return proto.CompactTextString(m) }
func (*CreatePodResponse) ProtoMessage()    {}
func (*CreatePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{4}
}

func (m *CreatePodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatePodResponse.Unmarshal(m, b)
}
func (m *CreatePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatePodResponse.Marshal(b, m, deterministic)
}
func (m *CreatePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatePodResponse.Merge(m, src)
}
func (m *CreatePodResponse) XXX_Size() int {
	return xxx_messageInfo_CreatePodResponse.Size(m)
}
func (m *CreatePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreatePodResponse proto.InternalMessageInfo

type UpdatePodRequest struct {
	Pod                  *v1.Pod  `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePodRequest) Reset()         { *m = UpdatePodRequest{} }
func (m *UpdatePodRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePodRequest) ProtoMessage()    {}
func (*UpdatePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{5}
}

func (m *UpdatePodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePodRequest.Unmarshal(m, b)
}
func (m *UpdatePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePodRequest.Marshal(b, m, deterministic)
}
func (m *UpdatePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePodRequest.Merge(m, src)
}
func (m *UpdatePodRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePodRequest.Size(m)
}
func (m *UpdatePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePodRequest proto.InternalMessageInfo

func (m *UpdatePodRequest) GetPod() *v1.Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

type UpdatePodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePodResponse) Reset()         { *m = UpdatePodResponse{} }
func (m *UpdatePodResponse) String() string { return proto.CompactTextString(m) }
func (*UpdatePodResponse) ProtoMessage()    {}
func (*UpdatePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{6}
}

func (m *UpdatePodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePodResponse.Unmarshal(m, b)
}
func (m *UpdatePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePodResponse.Marshal(b, m, deterministic)
}
func (m *UpdatePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePodResponse.Merge(m, src)
}
func (m *UpdatePodResponse) XXX_Size() int {
	return xxx_messageInfo_UpdatePodResponse.Size(m)
}
func (m *UpdatePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePodResponse proto.InternalMessageInfo

type DeletePodRequest struct {
	Pod                  *v1.Pod  `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePodRequest) Reset()         { *m = DeletePodRequest{} }
func (m *DeletePodRequest) String() string { return proto.CompactTextString(m) }
func (*DeletePodRequest) ProtoMessage()    {}
func (*DeletePodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{7}
}

func (m *DeletePodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodRequest.Unmarshal(m, b)
}
func (m *DeletePodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodRequest.Marshal(b, m, deterministic)
}
func (m *DeletePodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodRequest.Merge(m, src)
}
func (m *DeletePodRequest) XXX_Size() int {
	return xxx_messageInfo_DeletePodRequest.Size(m)
}
func (m *DeletePodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodRequest proto.InternalMessageInfo

func (m *DeletePodRequest) GetPod() *v1.Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

type DeletePodResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeletePodResponse) Reset()         { *m = DeletePodResponse{} }
func (m *DeletePodResponse) String() string { return proto.CompactTextString(m) }
func (*DeletePodResponse) ProtoMessage()    {}
func (*DeletePodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{8}
}

func (m *DeletePodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeletePodResponse.Unmarshal(m, b)
}
func (m *DeletePodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeletePodResponse.Marshal(b, m, deterministic)
}
func (m *DeletePodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeletePodResponse.Merge(m, src)
}
func (m *DeletePodResponse) XXX_Size() int {
	return xxx_messageInfo_DeletePodResponse.Size(m)
}
func (m *DeletePodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeletePodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeletePodResponse proto.InternalMessageInfo

type GetPodRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPodRequest) Reset()         { *m = GetPodRequest{} }
func (m *GetPodRequest) String() string { return proto.CompactTextString(m) }
func (*GetPodRequest) ProtoMessage()    {}
func (*GetPodRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{9}
}

func (m *GetPodRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodRequest.Unmarshal(m, b)
}
func (m *GetPodRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodRequest.Marshal(b, m, deterministic)
}
func (m *GetPodRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodRequest.Merge(m, src)
}
func (m *GetPodRequest) XXX_Size() int {
	return xxx_messageInfo_GetPodRequest.Size(m)
}
func (m *GetPodRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodRequest proto.InternalMessageInfo

func (m *GetPodRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetPodRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPodResponse struct {
	Pod                  *v1.Pod  `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPodResponse) Reset()         { *m = GetPodResponse{} }
func (m *GetPodResponse) String() string { return proto.CompactTextString(m) }
func (*GetPodResponse) ProtoMessage()    {}
func (*GetPodResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{10}
}

func (m *GetPodResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodResponse.Unmarshal(m, b)
}
func (m *GetPodResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodResponse.Marshal(b, m, deterministic)
}
func (m *GetPodResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodResponse.Merge(m, src)
}
func (m *GetPodResponse) XXX_Size() int {
	return xxx_messageInfo_GetPodResponse.Size(m)
}
func (m *GetPodResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodResponse proto.InternalMessageInfo

func (m *GetPodResponse) GetPod() *v1.Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

type GetContainerLogsRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	PodName              string   `protobuf:"bytes,2,opt,name=podName,proto3" json:"podName,omitempty"`
	ContainerName        string   `protobuf:"bytes,3,opt,name=containerName,proto3" json:"containerName,omitempty"`
	Tail                 uint64   `protobuf:"varint,4,opt,name=tail,proto3" json:"tail,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainerLogsRequest) Reset()         { *m = GetContainerLogsRequest{} }
func (m *GetContainerLogsRequest) String() string { return proto.CompactTextString(m) }
func (*GetContainerLogsRequest) ProtoMessage()    {}
func (*GetContainerLogsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{11}
}

func (m *GetContainerLogsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerLogsRequest.Unmarshal(m, b)
}
func (m *GetContainerLogsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerLogsRequest.Marshal(b, m, deterministic)
}
func (m *GetContainerLogsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerLogsRequest.Merge(m, src)
}
func (m *GetContainerLogsRequest) XXX_Size() int {
	return xxx_messageInfo_GetContainerLogsRequest.Size(m)
}
func (m *GetContainerLogsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerLogsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerLogsRequest proto.InternalMessageInfo

func (m *GetContainerLogsRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetContainerLogsRequest) GetPodName() string {
	if m != nil {
		return m.PodName
	}
	return ""
}

func (m *GetContainerLogsRequest) GetContainerName() string {
	if m != nil {
		return m.ContainerName
	}
	return ""
}

func (m *GetContainerLogsRequest) GetTail() uint64 {
	if m != nil {
		return m.Tail
	}
	return 0
}

type GetContainerLogsResponse struct {
	Logs                 string   `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetContainerLogsResponse) Reset()         { *m = GetContainerLogsResponse{} }
func (m *GetContainerLogsResponse) String() string { return proto.CompactTextString(m) }
func (*GetContainerLogsResponse) ProtoMessage()    {}
func (*GetContainerLogsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{12}
}

func (m *GetContainerLogsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainerLogsResponse.Unmarshal(m, b)
}
func (m *GetContainerLogsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainerLogsResponse.Marshal(b, m, deterministic)
}
func (m *GetContainerLogsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainerLogsResponse.Merge(m, src)
}
func (m *GetContainerLogsResponse) XXX_Size() int {
	return xxx_messageInfo_GetContainerLogsResponse.Size(m)
}
func (m *GetContainerLogsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainerLogsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainerLogsResponse proto.InternalMessageInfo

func (m *GetContainerLogsResponse) GetLogs() string {
	if m != nil {
		return m.Logs
	}
	return ""
}

type GetPodStatusRequest struct {
	Namespace            string   `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPodStatusRequest) Reset()         { *m = GetPodStatusRequest{} }
func (m *GetPodStatusRequest) String() string { return proto.CompactTextString(m) }
func (*GetPodStatusRequest) ProtoMessage()    {}
func (*GetPodStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{13}
}

func (m *GetPodStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodStatusRequest.Unmarshal(m, b)
}
func (m *GetPodStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodStatusRequest.Marshal(b, m, deterministic)
}
func (m *GetPodStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodStatusRequest.Merge(m, src)
}
func (m *GetPodStatusRequest) XXX_Size() int {
	return xxx_messageInfo_GetPodStatusRequest.Size(m)
}
func (m *GetPodStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodStatusRequest proto.InternalMessageInfo

func (m *GetPodStatusRequest) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *GetPodStatusRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetPodStatusResponse struct {
	Status               *v1.PodStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetPodStatusResponse) Reset()         { *m = GetPodStatusResponse{} }
func (m *GetPodStatusResponse) String() string { return proto.CompactTextString(m) }
func (*GetPodStatusResponse) ProtoMessage()    {}
func (*GetPodStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{14}
}

func (m *GetPodStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodStatusResponse.Unmarshal(m, b)
}
func (m *GetPodStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodStatusResponse.Marshal(b, m, deterministic)
}
func (m *GetPodStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodStatusResponse.Merge(m, src)
}
func (m *GetPodStatusResponse) XXX_Size() int {
	return xxx_messageInfo_GetPodStatusResponse.Size(m)
}
func (m *GetPodStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodStatusResponse proto.InternalMessageInfo

func (m *GetPodStatusResponse) GetStatus() *v1.PodStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

type GetPodsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetPodsRequest) Reset()         { *m = GetPodsRequest{} }
func (m *GetPodsRequest) String() string { return proto.CompactTextString(m) }
func (*GetPodsRequest) ProtoMessage()    {}
func (*GetPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{15}
}

func (m *GetPodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodsRequest.Unmarshal(m, b)
}
func (m *GetPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodsRequest.Marshal(b, m, deterministic)
}
func (m *GetPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodsRequest.Merge(m, src)
}
func (m *GetPodsRequest) XXX_Size() int {
	return xxx_messageInfo_GetPodsRequest.Size(m)
}
func (m *GetPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodsRequest proto.InternalMessageInfo

type GetPodsResponse struct {
	Pods                 []*v1.Pod `protobuf:"bytes,1,rep,name=pods,proto3" json:"pods,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *GetPodsResponse) Reset()         { *m = GetPodsResponse{} }
func (m *GetPodsResponse) String() string { return proto.CompactTextString(m) }
func (*GetPodsResponse) ProtoMessage()    {}
func (*GetPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{16}
}

func (m *GetPodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetPodsResponse.Unmarshal(m, b)
}
func (m *GetPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetPodsResponse.Marshal(b, m, deterministic)
}
func (m *GetPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetPodsResponse.Merge(m, src)
}
func (m *GetPodsResponse) XXX_Size() int {
	return xxx_messageInfo_GetPodsResponse.Size(m)
}
func (m *GetPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetPodsResponse proto.InternalMessageInfo

func (m *GetPodsResponse) GetPods() []*v1.Pod {
	if m != nil {
		return m.Pods
	}
	return nil
}

type CapacityRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CapacityRequest) Reset()         { *m = CapacityRequest{} }
func (m *CapacityRequest) String() string { return proto.CompactTextString(m) }
func (*CapacityRequest) ProtoMessage()    {}
func (*CapacityRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{17}
}

func (m *CapacityRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapacityRequest.Unmarshal(m, b)
}
func (m *CapacityRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapacityRequest.Marshal(b, m, deterministic)
}
func (m *CapacityRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapacityRequest.Merge(m, src)
}
func (m *CapacityRequest) XXX_Size() int {
	return xxx_messageInfo_CapacityRequest.Size(m)
}
func (m *CapacityRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CapacityRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CapacityRequest proto.InternalMessageInfo

type CapacityResponse struct {
	// string is ResourceName
	// value is the canonical representation of the resource
	// as rendered from String()
	ResourceList         map[string]string `protobuf:"bytes,1,rep,name=resourceList,proto3" json:"resourceList,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *CapacityResponse) Reset()         { *m = CapacityResponse{} }
func (m *CapacityResponse) String() string { return proto.CompactTextString(m) }
func (*CapacityResponse) ProtoMessage()    {}
func (*CapacityResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{18}
}

func (m *CapacityResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CapacityResponse.Unmarshal(m, b)
}
func (m *CapacityResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CapacityResponse.Marshal(b, m, deterministic)
}
func (m *CapacityResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CapacityResponse.Merge(m, src)
}
func (m *CapacityResponse) XXX_Size() int {
	return xxx_messageInfo_CapacityResponse.Size(m)
}
func (m *CapacityResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CapacityResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CapacityResponse proto.InternalMessageInfo

func (m *CapacityResponse) GetResourceList() map[string]string {
	if m != nil {
		return m.ResourceList
	}
	return nil
}

type NodeConditionsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeConditionsRequest) Reset()         { *m = NodeConditionsRequest{} }
func (m *NodeConditionsRequest) String() string { return proto.CompactTextString(m) }
func (*NodeConditionsRequest) ProtoMessage()    {}
func (*NodeConditionsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{19}
}

func (m *NodeConditionsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConditionsRequest.Unmarshal(m, b)
}
func (m *NodeConditionsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConditionsRequest.Marshal(b, m, deterministic)
}
func (m *NodeConditionsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConditionsRequest.Merge(m, src)
}
func (m *NodeConditionsRequest) XXX_Size() int {
	return xxx_messageInfo_NodeConditionsRequest.Size(m)
}
func (m *NodeConditionsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConditionsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConditionsRequest proto.InternalMessageInfo

type NodeConditionsResponse struct {
	NodeConditions       []*v1.NodeCondition `protobuf:"bytes,1,rep,name=nodeConditions,proto3" json:"nodeConditions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}            `json:"-"`
	XXX_unrecognized     []byte              `json:"-"`
	XXX_sizecache        int32               `json:"-"`
}

func (m *NodeConditionsResponse) Reset()         { *m = NodeConditionsResponse{} }
func (m *NodeConditionsResponse) String() string { return proto.CompactTextString(m) }
func (*NodeConditionsResponse) ProtoMessage()    {}
func (*NodeConditionsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{20}
}

func (m *NodeConditionsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeConditionsResponse.Unmarshal(m, b)
}
func (m *NodeConditionsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeConditionsResponse.Marshal(b, m, deterministic)
}
func (m *NodeConditionsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeConditionsResponse.Merge(m, src)
}
func (m *NodeConditionsResponse) XXX_Size() int {
	return xxx_messageInfo_NodeConditionsResponse.Size(m)
}
func (m *NodeConditionsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeConditionsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeConditionsResponse proto.InternalMessageInfo

func (m *NodeConditionsResponse) GetNodeConditions() []*v1.NodeCondition {
	if m != nil {
		return m.NodeConditions
	}
	return nil
}

type NodeAddressesRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeAddressesRequest) Reset()         { *m = NodeAddressesRequest{} }
func (m *NodeAddressesRequest) String() string { return proto.CompactTextString(m) }
func (*NodeAddressesRequest) ProtoMessage()    {}
func (*NodeAddressesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{21}
}

func (m *NodeAddressesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddressesRequest.Unmarshal(m, b)
}
func (m *NodeAddressesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddressesRequest.Marshal(b, m, deterministic)
}
func (m *NodeAddressesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddressesRequest.Merge(m, src)
}
func (m *NodeAddressesRequest) XXX_Size() int {
	return xxx_messageInfo_NodeAddressesRequest.Size(m)
}
func (m *NodeAddressesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddressesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddressesRequest proto.InternalMessageInfo

type NodeAddressesResponse struct {
	NodeAddresses        []*v1.NodeAddress `protobuf:"bytes,1,rep,name=nodeAddresses,proto3" json:"nodeAddresses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *NodeAddressesResponse) Reset()         { *m = NodeAddressesResponse{} }
func (m *NodeAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*NodeAddressesResponse) ProtoMessage()    {}
func (*NodeAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{22}
}

func (m *NodeAddressesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeAddressesResponse.Unmarshal(m, b)
}
func (m *NodeAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeAddressesResponse.Marshal(b, m, deterministic)
}
func (m *NodeAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeAddressesResponse.Merge(m, src)
}
func (m *NodeAddressesResponse) XXX_Size() int {
	return xxx_messageInfo_NodeAddressesResponse.Size(m)
}
func (m *NodeAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeAddressesResponse proto.InternalMessageInfo

func (m *NodeAddressesResponse) GetNodeAddresses() []*v1.NodeAddress {
	if m != nil {
		return m.NodeAddresses
	}
	return nil
}

type NodeDaemonEndpointsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NodeDaemonEndpointsRequest) Reset()         { *m = NodeDaemonEndpointsRequest{} }
func (m *NodeDaemonEndpointsRequest) String() string { return proto.CompactTextString(m) }
func (*NodeDaemonEndpointsRequest) ProtoMessage()    {}
func (*NodeDaemonEndpointsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{23}
}

func (m *NodeDaemonEndpointsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDaemonEndpointsRequest.Unmarshal(m, b)
}
func (m *NodeDaemonEndpointsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDaemonEndpointsRequest.Marshal(b, m, deterministic)
}
func (m *NodeDaemonEndpointsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDaemonEndpointsRequest.Merge(m, src)
}
func (m *NodeDaemonEndpointsRequest) XXX_Size() int {
	return xxx_messageInfo_NodeDaemonEndpointsRequest.Size(m)
}
func (m *NodeDaemonEndpointsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDaemonEndpointsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDaemonEndpointsRequest proto.InternalMessageInfo

type NodeDaemonEndpointsResponse struct {
	NodeDaemonEndpoints  *v1.NodeDaemonEndpoints `protobuf:"bytes,1,opt,name=nodeDaemonEndpoints,proto3" json:"nodeDaemonEndpoints,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *NodeDaemonEndpointsResponse) Reset()         { *m = NodeDaemonEndpointsResponse{} }
func (m *NodeDaemonEndpointsResponse) String() string { return proto.CompactTextString(m) }
func (*NodeDaemonEndpointsResponse) ProtoMessage()    {}
func (*NodeDaemonEndpointsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{24}
}

func (m *NodeDaemonEndpointsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NodeDaemonEndpointsResponse.Unmarshal(m, b)
}
func (m *NodeDaemonEndpointsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NodeDaemonEndpointsResponse.Marshal(b, m, deterministic)
}
func (m *NodeDaemonEndpointsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeDaemonEndpointsResponse.Merge(m, src)
}
func (m *NodeDaemonEndpointsResponse) XXX_Size() int {
	return xxx_messageInfo_NodeDaemonEndpointsResponse.Size(m)
}
func (m *NodeDaemonEndpointsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeDaemonEndpointsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NodeDaemonEndpointsResponse proto.InternalMessageInfo

func (m *NodeDaemonEndpointsResponse) GetNodeDaemonEndpoints() *v1.NodeDaemonEndpoints {
	if m != nil {
		return m.NodeDaemonEndpoints
	}
	return nil
}

type OperatingSystemRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatingSystemRequest) Reset()         { *m = OperatingSystemRequest{} }
func (m *OperatingSystemRequest) String() string { return proto.CompactTextString(m) }
func (*OperatingSystemRequest) ProtoMessage()    {}
func (*OperatingSystemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{25}
}

func (m *OperatingSystemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatingSystemRequest.Unmarshal(m, b)
}
func (m *OperatingSystemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatingSystemRequest.Marshal(b, m, deterministic)
}
func (m *OperatingSystemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatingSystemRequest.Merge(m, src)
}
func (m *OperatingSystemRequest) XXX_Size() int {
	return xxx_messageInfo_OperatingSystemRequest.Size(m)
}
func (m *OperatingSystemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatingSystemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OperatingSystemRequest proto.InternalMessageInfo

type OperatingSystemResponse struct {
	OperatingSystem      string   `protobuf:"bytes,1,opt,name=operatingSystem,proto3" json:"operatingSystem,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OperatingSystemResponse) Reset()         { *m = OperatingSystemResponse{} }
func (m *OperatingSystemResponse) String() string { return proto.CompactTextString(m) }
func (*OperatingSystemResponse) ProtoMessage()    {}
func (*OperatingSystemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{26}
}

func (m *OperatingSystemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OperatingSystemResponse.Unmarshal(m, b)
}
func (m *OperatingSystemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OperatingSystemResponse.Marshal(b, m, deterministic)
}
func (m *OperatingSystemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OperatingSystemResponse.Merge(m, src)
}
func (m *OperatingSystemResponse) XXX_Size() int {
	return xxx_messageInfo_OperatingSystemResponse.Size(m)
}
func (m *OperatingSystemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_OperatingSystemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_OperatingSystemResponse proto.InternalMessageInfo

func (m *OperatingSystemResponse) GetOperatingSystem() string {
	if m != nil {
		return m.OperatingSystem
	}
	return ""
}

type PodNotifierProviderRegisterRequest struct {
	PodNotifierProviderBrokerId uint32   `protobuf:"varint,1,opt,name=podNotifierProviderBrokerId,proto3" json:"podNotifierProviderBrokerId,omitempty"`
	XXX_NoUnkeyedLiteral        struct{} `json:"-"`
	XXX_unrecognized            []byte   `json:"-"`
	XXX_sizecache               int32    `json:"-"`
}

func (m *PodNotifierProviderRegisterRequest) Reset()         { *m = PodNotifierProviderRegisterRequest{} }
func (m *PodNotifierProviderRegisterRequest) String() string { return proto.CompactTextString(m) }
func (*PodNotifierProviderRegisterRequest) ProtoMessage()    {}
func (*PodNotifierProviderRegisterRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{27}
}

func (m *PodNotifierProviderRegisterRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodNotifierProviderRegisterRequest.Unmarshal(m, b)
}
func (m *PodNotifierProviderRegisterRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodNotifierProviderRegisterRequest.Marshal(b, m, deterministic)
}
func (m *PodNotifierProviderRegisterRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodNotifierProviderRegisterRequest.Merge(m, src)
}
func (m *PodNotifierProviderRegisterRequest) XXX_Size() int {
	return xxx_messageInfo_PodNotifierProviderRegisterRequest.Size(m)
}
func (m *PodNotifierProviderRegisterRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PodNotifierProviderRegisterRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PodNotifierProviderRegisterRequest proto.InternalMessageInfo

func (m *PodNotifierProviderRegisterRequest) GetPodNotifierProviderBrokerId() uint32 {
	if m != nil {
		return m.PodNotifierProviderBrokerId
	}
	return 0
}

type PodNotifierProviderRegisterResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PodNotifierProviderRegisterResponse) Reset()         { *m = PodNotifierProviderRegisterResponse{} }
func (m *PodNotifierProviderRegisterResponse) String() string { return proto.CompactTextString(m) }
func (*PodNotifierProviderRegisterResponse) ProtoMessage()    {}
func (*PodNotifierProviderRegisterResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{28}
}

func (m *PodNotifierProviderRegisterResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PodNotifierProviderRegisterResponse.Unmarshal(m, b)
}
func (m *PodNotifierProviderRegisterResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PodNotifierProviderRegisterResponse.Marshal(b, m, deterministic)
}
func (m *PodNotifierProviderRegisterResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PodNotifierProviderRegisterResponse.Merge(m, src)
}
func (m *PodNotifierProviderRegisterResponse) XXX_Size() int {
	return xxx_messageInfo_PodNotifierProviderRegisterResponse.Size(m)
}
func (m *PodNotifierProviderRegisterResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PodNotifierProviderRegisterResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PodNotifierProviderRegisterResponse proto.InternalMessageInfo

type NotifyPodsRequest struct {
	Pod                  *v1.Pod  `protobuf:"bytes,1,opt,name=pod,proto3" json:"pod,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyPodsRequest) Reset()         { *m = NotifyPodsRequest{} }
func (m *NotifyPodsRequest) String() string { return proto.CompactTextString(m) }
func (*NotifyPodsRequest) ProtoMessage()    {}
func (*NotifyPodsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{29}
}

func (m *NotifyPodsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPodsRequest.Unmarshal(m, b)
}
func (m *NotifyPodsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPodsRequest.Marshal(b, m, deterministic)
}
func (m *NotifyPodsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPodsRequest.Merge(m, src)
}
func (m *NotifyPodsRequest) XXX_Size() int {
	return xxx_messageInfo_NotifyPodsRequest.Size(m)
}
func (m *NotifyPodsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPodsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPodsRequest proto.InternalMessageInfo

func (m *NotifyPodsRequest) GetPod() *v1.Pod {
	if m != nil {
		return m.Pod
	}
	return nil
}

type NotifyPodsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NotifyPodsResponse) Reset()         { *m = NotifyPodsResponse{} }
func (m *NotifyPodsResponse) String() string { return proto.CompactTextString(m) }
func (*NotifyPodsResponse) ProtoMessage()    {}
func (*NotifyPodsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_22a625af4bc1cc87, []int{30}
}

func (m *NotifyPodsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NotifyPodsResponse.Unmarshal(m, b)
}
func (m *NotifyPodsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NotifyPodsResponse.Marshal(b, m, deterministic)
}
func (m *NotifyPodsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NotifyPodsResponse.Merge(m, src)
}
func (m *NotifyPodsResponse) XXX_Size() int {
	return xxx_messageInfo_NotifyPodsResponse.Size(m)
}
func (m *NotifyPodsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_NotifyPodsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_NotifyPodsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*InitConfig)(nil), "pluginproto.InitConfig")
	proto.RegisterType((*ProviderRegisterRequest)(nil), "pluginproto.ProviderRegisterRequest")
	proto.RegisterType((*ProviderRegisterResponse)(nil), "pluginproto.ProviderRegisterResponse")
	proto.RegisterType((*CreatePodRequest)(nil), "pluginproto.CreatePodRequest")
	proto.RegisterType((*CreatePodResponse)(nil), "pluginproto.CreatePodResponse")
	proto.RegisterType((*UpdatePodRequest)(nil), "pluginproto.UpdatePodRequest")
	proto.RegisterType((*UpdatePodResponse)(nil), "pluginproto.UpdatePodResponse")
	proto.RegisterType((*DeletePodRequest)(nil), "pluginproto.DeletePodRequest")
	proto.RegisterType((*DeletePodResponse)(nil), "pluginproto.DeletePodResponse")
	proto.RegisterType((*GetPodRequest)(nil), "pluginproto.GetPodRequest")
	proto.RegisterType((*GetPodResponse)(nil), "pluginproto.GetPodResponse")
	proto.RegisterType((*GetContainerLogsRequest)(nil), "pluginproto.GetContainerLogsRequest")
	proto.RegisterType((*GetContainerLogsResponse)(nil), "pluginproto.GetContainerLogsResponse")
	proto.RegisterType((*GetPodStatusRequest)(nil), "pluginproto.GetPodStatusRequest")
	proto.RegisterType((*GetPodStatusResponse)(nil), "pluginproto.GetPodStatusResponse")
	proto.RegisterType((*GetPodsRequest)(nil), "pluginproto.GetPodsRequest")
	proto.RegisterType((*GetPodsResponse)(nil), "pluginproto.GetPodsResponse")
	proto.RegisterType((*CapacityRequest)(nil), "pluginproto.CapacityRequest")
	proto.RegisterType((*CapacityResponse)(nil), "pluginproto.CapacityResponse")
	proto.RegisterMapType((map[string]string)(nil), "pluginproto.CapacityResponse.ResourceListEntry")
	proto.RegisterType((*NodeConditionsRequest)(nil), "pluginproto.NodeConditionsRequest")
	proto.RegisterType((*NodeConditionsResponse)(nil), "pluginproto.NodeConditionsResponse")
	proto.RegisterType((*NodeAddressesRequest)(nil), "pluginproto.NodeAddressesRequest")
	proto.RegisterType((*NodeAddressesResponse)(nil), "pluginproto.NodeAddressesResponse")
	proto.RegisterType((*NodeDaemonEndpointsRequest)(nil), "pluginproto.NodeDaemonEndpointsRequest")
	proto.RegisterType((*NodeDaemonEndpointsResponse)(nil), "pluginproto.NodeDaemonEndpointsResponse")
	proto.RegisterType((*OperatingSystemRequest)(nil), "pluginproto.OperatingSystemRequest")
	proto.RegisterType((*OperatingSystemResponse)(nil), "pluginproto.OperatingSystemResponse")
	proto.RegisterType((*PodNotifierProviderRegisterRequest)(nil), "pluginproto.PodNotifierProviderRegisterRequest")
	proto.RegisterType((*PodNotifierProviderRegisterResponse)(nil), "pluginproto.PodNotifierProviderRegisterResponse")
	proto.RegisterType((*NotifyPodsRequest)(nil), "pluginproto.NotifyPodsRequest")
	proto.RegisterType((*NotifyPodsResponse)(nil), "pluginproto.NotifyPodsResponse")
}

func init() { proto.RegisterFile("plugin.proto", fileDescriptor_22a625af4bc1cc87) }

var fileDescriptor_22a625af4bc1cc87 = []byte{
	// 1012 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdb, 0x6e, 0xdc, 0x44,
	0x18, 0xd6, 0x36, 0x9b, 0x64, 0xf3, 0x37, 0x9b, 0x6c, 0x26, 0x21, 0x6b, 0x39, 0x87, 0x26, 0xd3,
	0x54, 0x0d, 0x42, 0xf2, 0xd2, 0x22, 0x44, 0x05, 0xa2, 0x90, 0x6e, 0xa2, 0x28, 0xa8, 0x0d, 0x2b,
	0x47, 0x80, 0x8a, 0x10, 0x68, 0xba, 0x9e, 0x2c, 0xa3, 0xec, 0xce, 0x18, 0x7b, 0x36, 0x62, 0xef,
	0xb9, 0xe3, 0x45, 0xb8, 0xe6, 0x35, 0x78, 0x29, 0x64, 0x7b, 0x7c, 0x98, 0xb1, 0xbd, 0xe9, 0xe1,
	0xca, 0xf6, 0x7f, 0xf8, 0xfe, 0xc3, 0x8c, 0xbf, 0x0f, 0x56, 0xfd, 0xf1, 0x74, 0xc4, 0xb8, 0xe3,
	0x07, 0x42, 0x0a, 0x74, 0x3f, 0xf9, 0x8a, 0x3f, 0x6c, 0x7c, 0xf3, 0x2c, 0x74, 0x98, 0xe8, 0x11,
	0x9f, 0xf5, 0x86, 0x22, 0xa0, 0xbd, 0xdb, 0x27, 0xbd, 0x11, 0xe5, 0x34, 0x20, 0x92, 0x7a, 0x49,
	0x02, 0xfe, 0xb7, 0x01, 0x70, 0xc1, 0x99, 0xec, 0x0b, 0x7e, 0xcd, 0x46, 0x68, 0x1f, 0x60, 0x18,
	0xbf, 0x0d, 0x88, 0xfc, 0xdd, 0x6a, 0x1c, 0x34, 0x8e, 0x57, 0xdc, 0x82, 0x05, 0xd9, 0xd0, 0xe2,
	0xc2, 0xa3, 0x97, 0x64, 0x42, 0xad, 0x7b, 0xb1, 0x37, 0xfb, 0x46, 0xc7, 0xb0, 0x2e, 0xfc, 0x08,
	0x9c, 0xf1, 0xd1, 0xd5, 0x2c, 0x94, 0x74, 0x62, 0x2d, 0xc4, 0x21, 0xa6, 0x39, 0xaa, 0xc2, 0xb8,
	0xa4, 0x01, 0x27, 0xe3, 0x8b, 0x81, 0xd5, 0x4c, 0xaa, 0xe4, 0x96, 0xc8, 0x7f, 0x4a, 0xe8, 0x44,
	0xf0, 0x81, 0x08, 0xa4, 0xb5, 0x78, 0xd0, 0x38, 0x5e, 0x74, 0x0b, 0x16, 0xec, 0x42, 0x77, 0x10,
	0x88, 0x5b, 0xe6, 0xd1, 0xc0, 0xa5, 0x23, 0x16, 0xca, 0xe8, 0xf9, 0xc7, 0x94, 0x86, 0x12, 0x7d,
	0x11, 0x41, 0xa7, 0xe3, 0xc4, 0x03, 0xdc, 0x7f, 0xda, 0x75, 0x0a, 0x5b, 0x71, 0xf2, 0x69, 0xdd,
	0x42, 0x28, 0xb6, 0xc1, 0x2a, 0x63, 0x86, 0xbe, 0xe0, 0x21, 0xc5, 0x5f, 0x43, 0xa7, 0x1f, 0x50,
	0x22, 0xe9, 0x40, 0x78, 0x69, 0xa1, 0x8f, 0x61, 0xc1, 0x17, 0x5e, 0x56, 0x21, 0x59, 0xb5, 0x43,
	0x7c, 0xe6, 0x44, 0xab, 0x76, 0x6e, 0x9f, 0x38, 0x51, 0x70, 0x14, 0x83, 0x37, 0x61, 0xa3, 0x90,
	0x9e, 0x63, 0xfe, 0xe0, 0x7b, 0x1f, 0x82, 0x59, 0x48, 0xcf, 0x31, 0x4f, 0xe9, 0x98, 0x7e, 0x00,
	0x66, 0x21, 0x5d, 0x61, 0x9e, 0x40, 0xfb, 0x9c, 0xca, 0x02, 0xe0, 0x2e, 0xac, 0x70, 0x32, 0xa1,
	0xa1, 0x4f, 0x86, 0x54, 0xdd, 0x90, 0xdc, 0x80, 0x10, 0x34, 0x79, 0x7e, 0x39, 0xe2, 0x77, 0xfc,
	0x15, 0xac, 0xa5, 0x10, 0x09, 0xe8, 0xbb, 0x34, 0xf5, 0x77, 0x03, 0xba, 0xe7, 0x34, 0x3a, 0x25,
	0x49, 0x18, 0xa7, 0xc1, 0x4b, 0x31, 0x0a, 0xdf, 0xae, 0x15, 0x0b, 0x96, 0x7d, 0xe1, 0x15, 0xae,
	0x6a, 0xfa, 0x89, 0x8e, 0xa0, 0x3d, 0x4c, 0xf1, 0x62, 0x7f, 0x72, 0x4f, 0x75, 0x63, 0x34, 0x8a,
	0x24, 0x6c, 0x1c, 0xdf, 0xcf, 0xa6, 0x1b, 0xbf, 0x63, 0x07, 0xac, 0x72, 0x33, 0x6a, 0x28, 0x04,
	0xcd, 0xb1, 0x18, 0x85, 0xaa, 0x91, 0xf8, 0x1d, 0x9f, 0xc3, 0x66, 0x32, 0xfa, 0x95, 0x24, 0x72,
	0x1a, 0xbe, 0xff, 0x0e, 0x5f, 0xc1, 0x96, 0x0e, 0xa4, 0x8a, 0x7e, 0x0e, 0x4b, 0x61, 0x6c, 0x51,
	0xcb, 0xdc, 0xab, 0x59, 0xa6, 0x4a, 0x53, 0xc1, 0xb8, 0x93, 0x1e, 0x49, 0xda, 0x12, 0x7e, 0x0e,
	0xeb, 0x99, 0x45, 0x61, 0x7f, 0x02, 0x4d, 0x5f, 0x78, 0x11, 0xf2, 0xc2, 0xbc, 0x63, 0x8a, 0x83,
	0xf0, 0x06, 0xac, 0xf7, 0x89, 0x4f, 0x86, 0x4c, 0xce, 0x52, 0xc8, 0x7f, 0x1a, 0xd0, 0xc9, 0x6d,
	0x0a, 0xf4, 0x0a, 0x56, 0x03, 0x1a, 0x8a, 0x69, 0x30, 0xa4, 0x2f, 0x59, 0x28, 0x15, 0x78, 0x4f,
	0xfb, 0x45, 0xcd, 0x24, 0xc7, 0x2d, 0x64, 0x9c, 0x71, 0x19, 0xcc, 0x5c, 0x0d, 0xc4, 0xfe, 0x06,
	0x36, 0x4a, 0x21, 0xa8, 0x03, 0x0b, 0x37, 0x74, 0xa6, 0xd6, 0x1b, 0xbd, 0xa2, 0x2d, 0x58, 0xbc,
	0x25, 0xe3, 0x69, 0xba, 0xd9, 0xe4, 0xe3, 0xcb, 0x7b, 0xcf, 0x1a, 0xb8, 0x0b, 0x1f, 0x5d, 0x0a,
	0x8f, 0xf6, 0x05, 0xf7, 0x98, 0x64, 0x82, 0x67, 0x6b, 0x19, 0xc2, 0xb6, 0xe9, 0x50, 0x83, 0x5c,
	0xc0, 0x1a, 0xd7, 0x3c, 0x6a, 0x94, 0xc3, 0xaa, 0x3d, 0x69, 0x18, 0xae, 0x91, 0x88, 0xb7, 0x61,
	0x2b, 0x0a, 0x38, 0xf1, 0xbc, 0x80, 0x86, 0x21, 0xcd, 0x8a, 0xff, 0x9a, 0x74, 0x55, 0xb0, 0xab,
	0xda, 0x67, 0xd0, 0xe6, 0x45, 0x87, 0x2a, 0xfd, 0xa0, 0xae, 0xb4, 0x0a, 0x74, 0xf5, 0x2c, 0xbc,
	0x0b, 0x76, 0xe4, 0x4d, 0x98, 0xf5, 0x8c, 0x7b, 0xbe, 0x60, 0x5c, 0x66, 0xd5, 0xff, 0x84, 0x9d,
	0x4a, 0xaf, 0xea, 0xe1, 0x35, 0x6c, 0xf2, 0xb2, 0x5b, 0x5d, 0xc3, 0xc7, 0x75, 0x9d, 0x98, 0x68,
	0x55, 0x18, 0xd8, 0x82, 0xed, 0xef, 0x75, 0xc9, 0x48, 0x7b, 0xea, 0x43, 0xb7, 0xe4, 0x51, 0xfd,
	0x54, 0xc8, 0x4f, 0xa3, 0x52, 0x7e, 0xf0, 0x35, 0xe0, 0x81, 0xf0, 0x2e, 0x85, 0x64, 0xd7, 0x8c,
	0x06, 0x75, 0x4a, 0xf2, 0x2d, 0xec, 0xf8, 0xe5, 0xa8, 0x17, 0x81, 0xb8, 0xa1, 0xc1, 0x45, 0xc2,
	0x5d, 0x6d, 0x77, 0x5e, 0x08, 0x7e, 0x04, 0x0f, 0xe7, 0xd6, 0x51, 0x0c, 0xfb, 0x1c, 0x36, 0xe2,
	0x98, 0x59, 0xe1, 0x77, 0x7c, 0x17, 0x86, 0xdc, 0x02, 0x54, 0xcc, 0x4f, 0x50, 0x9f, 0xfe, 0xd7,
	0x82, 0x56, 0x5a, 0x12, 0xfd, 0x04, 0xad, 0xb4, 0x2c, 0x3a, 0xd2, 0x7e, 0xb5, 0x9a, 0xe9, 0xed,
	0x47, 0x77, 0x44, 0xa9, 0xa5, 0x7f, 0x07, 0x2b, 0x99, 0xb4, 0xa1, 0x3d, 0xfd, 0x27, 0x36, 0x14,
	0xd3, 0xde, 0xaf, 0x73, 0xe7, 0x58, 0x99, 0xa4, 0x19, 0x58, 0xa6, 0x52, 0x1a, 0x58, 0x25, 0x25,
	0x8c, 0xb0, 0x32, 0x29, 0x33, 0xb0, 0x4c, 0x85, 0x34, 0xb0, 0x4a, 0x0a, 0x88, 0x4e, 0x60, 0x29,
	0x61, 0x46, 0x64, 0x6b, 0x91, 0x9a, 0x2c, 0xda, 0x3b, 0x95, 0x3e, 0x05, 0xf1, 0x1b, 0x74, 0x4c,
	0xd9, 0x30, 0xce, 0xa1, 0x46, 0xe2, 0x8c, 0x73, 0xa8, 0xd5, 0x9e, 0x2b, 0x58, 0x2d, 0xca, 0x03,
	0x3a, 0xa8, 0xe8, 0x46, 0x93, 0x20, 0xfb, 0x70, 0x4e, 0x84, 0x02, 0x3d, 0x85, 0x65, 0x25, 0x09,
	0xa8, 0x6a, 0xba, 0x0c, 0x6a, 0xb7, 0xda, 0xa9, 0x50, 0xce, 0xa1, 0x95, 0xf2, 0x39, 0xda, 0xad,
	0xa1, 0xf9, 0x04, 0x67, 0x6f, 0xae, 0x08, 0xa0, 0xd7, 0xb0, 0xa6, 0x53, 0x31, 0xc2, 0x5a, 0x42,
	0x25, 0x81, 0xdb, 0x0f, 0xe7, 0xc6, 0x28, 0xe8, 0x1f, 0xa1, 0xad, 0x11, 0x2d, 0x3a, 0x2c, 0x65,
	0x99, 0xe4, 0x6c, 0xe3, 0x79, 0x21, 0x0a, 0x97, 0x25, 0xc4, 0x9e, 0xf1, 0x5b, 0x98, 0x10, 0x1c,
	0x7a, 0x5c, 0xca, 0xad, 0xe6, 0x60, 0xfb, 0xf8, 0xee, 0x40, 0x55, 0xea, 0x17, 0x58, 0x37, 0x98,
	0x11, 0xe9, 0xa3, 0x57, 0x33, 0xaa, 0x7d, 0x34, 0x3f, 0x48, 0xb1, 0xc9, 0x5f, 0x0d, 0xd8, 0xac,
	0xe0, 0x32, 0x34, 0x29, 0x10, 0x8b, 0xae, 0xe1, 0x77, 0x33, 0xac, 0xfd, 0xe9, 0xdb, 0x27, 0xa8,
	0x36, 0x3c, 0xad, 0x8b, 0x3e, 0x19, 0x8f, 0xdf, 0x90, 0xe1, 0x0d, 0x7a, 0x05, 0x90, 0x33, 0x20,
	0xda, 0x37, 0x76, 0x66, 0x50, 0xab, 0xfd, 0xa0, 0xd6, 0x9f, 0x54, 0x79, 0xb1, 0xfc, 0xf3, 0x62,
	0xec, 0x7b, 0xb3, 0x14, 0x3f, 0x3e, 0xfb, 0x3f, 0x00, 0x00, 0xff, 0xff, 0x41, 0x1d, 0xda, 0x69,
	0x64, 0x0d, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ProviderClient is the client API for Provider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ProviderClient interface {
	Register(ctx context.Context, in *ProviderRegisterRequest, opts ...grpc.CallOption) (*ProviderRegisterResponse, error)
	CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*CreatePodResponse, error)
	UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...grpc.CallOption) (*UpdatePodResponse, error)
	DeletePod(ctx context.Context, in *DeletePodRequest, opts ...grpc.CallOption) (*DeletePodResponse, error)
	GetPod(ctx context.Context, in *GetPodRequest, opts ...grpc.CallOption) (*GetPodResponse, error)
	GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error)
	GetPodStatus(ctx context.Context, in *GetPodStatusRequest, opts ...grpc.CallOption) (*GetPodStatusResponse, error)
	GetPods(ctx context.Context, in *GetPodsRequest, opts ...grpc.CallOption) (*GetPodsResponse, error)
	Capacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*CapacityResponse, error)
	NodeConditions(ctx context.Context, in *NodeConditionsRequest, opts ...grpc.CallOption) (*NodeConditionsResponse, error)
	NodeAddresses(ctx context.Context, in *NodeAddressesRequest, opts ...grpc.CallOption) (*NodeAddressesResponse, error)
	NodeDaemonEndspoints(ctx context.Context, in *NodeDaemonEndpointsRequest, opts ...grpc.CallOption) (*NodeDaemonEndpointsResponse, error)
	OperatingSystem(ctx context.Context, in *OperatingSystemRequest, opts ...grpc.CallOption) (*OperatingSystemResponse, error)
}

type providerClient struct {
	cc *grpc.ClientConn
}

func NewProviderClient(cc *grpc.ClientConn) ProviderClient {
	return &providerClient{cc}
}

func (c *providerClient) Register(ctx context.Context, in *ProviderRegisterRequest, opts ...grpc.CallOption) (*ProviderRegisterResponse, error) {
	out := new(ProviderRegisterResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) CreatePod(ctx context.Context, in *CreatePodRequest, opts ...grpc.CallOption) (*CreatePodResponse, error) {
	out := new(CreatePodResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/CreatePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) UpdatePod(ctx context.Context, in *UpdatePodRequest, opts ...grpc.CallOption) (*UpdatePodResponse, error) {
	out := new(UpdatePodResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/UpdatePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) DeletePod(ctx context.Context, in *DeletePodRequest, opts ...grpc.CallOption) (*DeletePodResponse, error) {
	out := new(DeletePodResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/DeletePod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetPod(ctx context.Context, in *GetPodRequest, opts ...grpc.CallOption) (*GetPodResponse, error) {
	out := new(GetPodResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/GetPod", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetContainerLogs(ctx context.Context, in *GetContainerLogsRequest, opts ...grpc.CallOption) (*GetContainerLogsResponse, error) {
	out := new(GetContainerLogsResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/GetContainerLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetPodStatus(ctx context.Context, in *GetPodStatusRequest, opts ...grpc.CallOption) (*GetPodStatusResponse, error) {
	out := new(GetPodStatusResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/GetPodStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) GetPods(ctx context.Context, in *GetPodsRequest, opts ...grpc.CallOption) (*GetPodsResponse, error) {
	out := new(GetPodsResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/GetPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) Capacity(ctx context.Context, in *CapacityRequest, opts ...grpc.CallOption) (*CapacityResponse, error) {
	out := new(CapacityResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/Capacity", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) NodeConditions(ctx context.Context, in *NodeConditionsRequest, opts ...grpc.CallOption) (*NodeConditionsResponse, error) {
	out := new(NodeConditionsResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/NodeConditions", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) NodeAddresses(ctx context.Context, in *NodeAddressesRequest, opts ...grpc.CallOption) (*NodeAddressesResponse, error) {
	out := new(NodeAddressesResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/NodeAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) NodeDaemonEndspoints(ctx context.Context, in *NodeDaemonEndpointsRequest, opts ...grpc.CallOption) (*NodeDaemonEndpointsResponse, error) {
	out := new(NodeDaemonEndpointsResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/NodeDaemonEndspoints", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *providerClient) OperatingSystem(ctx context.Context, in *OperatingSystemRequest, opts ...grpc.CallOption) (*OperatingSystemResponse, error) {
	out := new(OperatingSystemResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.Provider/OperatingSystem", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProviderServer is the server API for Provider service.
type ProviderServer interface {
	Register(context.Context, *ProviderRegisterRequest) (*ProviderRegisterResponse, error)
	CreatePod(context.Context, *CreatePodRequest) (*CreatePodResponse, error)
	UpdatePod(context.Context, *UpdatePodRequest) (*UpdatePodResponse, error)
	DeletePod(context.Context, *DeletePodRequest) (*DeletePodResponse, error)
	GetPod(context.Context, *GetPodRequest) (*GetPodResponse, error)
	GetContainerLogs(context.Context, *GetContainerLogsRequest) (*GetContainerLogsResponse, error)
	GetPodStatus(context.Context, *GetPodStatusRequest) (*GetPodStatusResponse, error)
	GetPods(context.Context, *GetPodsRequest) (*GetPodsResponse, error)
	Capacity(context.Context, *CapacityRequest) (*CapacityResponse, error)
	NodeConditions(context.Context, *NodeConditionsRequest) (*NodeConditionsResponse, error)
	NodeAddresses(context.Context, *NodeAddressesRequest) (*NodeAddressesResponse, error)
	NodeDaemonEndspoints(context.Context, *NodeDaemonEndpointsRequest) (*NodeDaemonEndpointsResponse, error)
	OperatingSystem(context.Context, *OperatingSystemRequest) (*OperatingSystemResponse, error)
}

func RegisterProviderServer(s *grpc.Server, srv ProviderServer) {
	s.RegisterService(&_Provider_serviceDesc, srv)
}

func _Provider_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ProviderRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Register(ctx, req.(*ProviderRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_CreatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).CreatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/CreatePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).CreatePod(ctx, req.(*CreatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_UpdatePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).UpdatePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/UpdatePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).UpdatePod(ctx, req.(*UpdatePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_DeletePod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).DeletePod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/DeletePod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).DeletePod(ctx, req.(*DeletePodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetPod_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).GetPod(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/GetPod",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).GetPod(ctx, req.(*GetPodRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetContainerLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainerLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).GetContainerLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/GetContainerLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).GetContainerLogs(ctx, req.(*GetContainerLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetPodStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).GetPodStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/GetPodStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).GetPodStatus(ctx, req.(*GetPodStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_GetPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).GetPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/GetPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).GetPods(ctx, req.(*GetPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_Capacity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CapacityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).Capacity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/Capacity",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).Capacity(ctx, req.(*CapacityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_NodeConditions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeConditionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).NodeConditions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/NodeConditions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).NodeConditions(ctx, req.(*NodeConditionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_NodeAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeAddressesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).NodeAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/NodeAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).NodeAddresses(ctx, req.(*NodeAddressesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_NodeDaemonEndspoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NodeDaemonEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).NodeDaemonEndspoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/NodeDaemonEndspoints",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).NodeDaemonEndspoints(ctx, req.(*NodeDaemonEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Provider_OperatingSystem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperatingSystemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProviderServer).OperatingSystem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.Provider/OperatingSystem",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProviderServer).OperatingSystem(ctx, req.(*OperatingSystemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Provider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginproto.Provider",
	HandlerType: (*ProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _Provider_Register_Handler,
		},
		{
			MethodName: "CreatePod",
			Handler:    _Provider_CreatePod_Handler,
		},
		{
			MethodName: "UpdatePod",
			Handler:    _Provider_UpdatePod_Handler,
		},
		{
			MethodName: "DeletePod",
			Handler:    _Provider_DeletePod_Handler,
		},
		{
			MethodName: "GetPod",
			Handler:    _Provider_GetPod_Handler,
		},
		{
			MethodName: "GetContainerLogs",
			Handler:    _Provider_GetContainerLogs_Handler,
		},
		{
			MethodName: "GetPodStatus",
			Handler:    _Provider_GetPodStatus_Handler,
		},
		{
			MethodName: "GetPods",
			Handler:    _Provider_GetPods_Handler,
		},
		{
			MethodName: "Capacity",
			Handler:    _Provider_Capacity_Handler,
		},
		{
			MethodName: "NodeConditions",
			Handler:    _Provider_NodeConditions_Handler,
		},
		{
			MethodName: "NodeAddresses",
			Handler:    _Provider_NodeAddresses_Handler,
		},
		{
			MethodName: "NodeDaemonEndspoints",
			Handler:    _Provider_NodeDaemonEndspoints_Handler,
		},
		{
			MethodName: "OperatingSystem",
			Handler:    _Provider_OperatingSystem_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// PodNotifierProviderClient is the client API for PodNotifierProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodNotifierProviderClient interface {
	Register(ctx context.Context, in *PodNotifierProviderRegisterRequest, opts ...grpc.CallOption) (*PodNotifierProviderRegisterResponse, error)
}

type podNotifierProviderClient struct {
	cc *grpc.ClientConn
}

func NewPodNotifierProviderClient(cc *grpc.ClientConn) PodNotifierProviderClient {
	return &podNotifierProviderClient{cc}
}

func (c *podNotifierProviderClient) Register(ctx context.Context, in *PodNotifierProviderRegisterRequest, opts ...grpc.CallOption) (*PodNotifierProviderRegisterResponse, error) {
	out := new(PodNotifierProviderRegisterResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.PodNotifierProvider/Register", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodNotifierProviderServer is the server API for PodNotifierProvider service.
type PodNotifierProviderServer interface {
	Register(context.Context, *PodNotifierProviderRegisterRequest) (*PodNotifierProviderRegisterResponse, error)
}

func RegisterPodNotifierProviderServer(s *grpc.Server, srv PodNotifierProviderServer) {
	s.RegisterService(&_PodNotifierProvider_serviceDesc, srv)
}

func _PodNotifierProvider_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PodNotifierProviderRegisterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNotifierProviderServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.PodNotifierProvider/Register",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNotifierProviderServer).Register(ctx, req.(*PodNotifierProviderRegisterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PodNotifierProvider_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginproto.PodNotifierProvider",
	HandlerType: (*PodNotifierProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _PodNotifierProvider_Register_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}

// PodNotifierCallbackClient is the client API for PodNotifierCallback service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PodNotifierCallbackClient interface {
	NotifyPods(ctx context.Context, in *NotifyPodsRequest, opts ...grpc.CallOption) (*NotifyPodsResponse, error)
}

type podNotifierCallbackClient struct {
	cc *grpc.ClientConn
}

func NewPodNotifierCallbackClient(cc *grpc.ClientConn) PodNotifierCallbackClient {
	return &podNotifierCallbackClient{cc}
}

func (c *podNotifierCallbackClient) NotifyPods(ctx context.Context, in *NotifyPodsRequest, opts ...grpc.CallOption) (*NotifyPodsResponse, error) {
	out := new(NotifyPodsResponse)
	err := c.cc.Invoke(ctx, "/pluginproto.PodNotifierCallback/NotifyPods", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PodNotifierCallbackServer is the server API for PodNotifierCallback service.
type PodNotifierCallbackServer interface {
	NotifyPods(context.Context, *NotifyPodsRequest) (*NotifyPodsResponse, error)
}

func RegisterPodNotifierCallbackServer(s *grpc.Server, srv PodNotifierCallbackServer) {
	s.RegisterService(&_PodNotifierCallback_serviceDesc, srv)
}

func _PodNotifierCallback_NotifyPods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyPodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PodNotifierCallbackServer).NotifyPods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pluginproto.PodNotifierCallback/NotifyPods",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PodNotifierCallbackServer).NotifyPods(ctx, req.(*NotifyPodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PodNotifierCallback_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pluginproto.PodNotifierCallback",
	HandlerType: (*PodNotifierCallbackServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NotifyPods",
			Handler:    _PodNotifierCallback_NotifyPods_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "plugin.proto",
}
