---
apiVersion: v1
kind: Pod
metadata:
  name: vkubelet-mock-0
spec:
  serviceAccountName: virtual-kubelet
  containers:
  - name: vkubelet-mock-0
    image: virtual-kubelet
    # "IfNotPresent" is used to prevent Minikube from trying to pull from the registry (and failing) in the first place.
    imagePullPolicy: IfNotPresent
    args:
    - /virtual-kubelet
    - --nodename
    - vkubelet-mock-0
    - --provider
    - mock
    - --provider-config
    - /vkubelet-mock-cfg.json
    - --startup-timeout
    - 10s
    - --klog.v
    - "2"
    - --klog.logtostderr
    - --log-level
    - debug
    env:
    - name: VKUBELET_POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: KUBELET_PORT
      value: "10350"
    ports:
    - name: metrics
      containerPort: 10255
    - name: api
      containerPort: 10350
    readinessProbe:
      httpGet:
        path: /stats/summary
        port: metrics